### PR TITLE
Various AXL updates 

### PR DESCRIPTION
**Pull request by mcreixell**
- Update figures 1&2 (completed)
- Analyze Luminex time series downstream kinases (in progress)
- Clean up previous Luminex data (stored in notebook for now)
- Re-organize past drug response assays (stored in notebook for now)

### CODE REVIEW

**Comment by mcreixell** [comment]
The notebook with the code to generate the tensor is in `downstream_dynamics.ipynb`. Let me know if this looks right or not. Also haven't added any labels per axis but these are really easy to extract from the original 2D data set.

**Comment by aarmey** [comment]
Ok, I added the parafac call and some example plots of the output. The "2" in the parafac line sets the number of components.

First question—how is this data normalized? From the results I wasn't sure that it has been.

**Comment by mcreixell** [comment]
Thank you. This is not normalized, it's the raw signal.

**Comment by aarmey** [comment]
Ok, you probably want to z-score each phosphosite across conditions. Right now I think one bead region has a lot more signal, and that's pretty much all parafac is explaining.

**Comment by mcreixell** [comment]
I've zscored and added AXL&YAP which I missed in Scott's spreadsheet. Is an R2X of 0.315 acceptable? I also uncommented the PCA analysis but still a bit hard to interpret.

**Comment by aarmey** [comment]
This works like PCA—you can vary the number of components which will change R2X.

**Comment by mcreixell** [comment]
Perfect, with 6 components we get ~62%. Is there a notebook I can check to try to replicate an analysis/interpretation of parafac?

**Comment by aarmey** [comment]
Brian has a draft of an example notebook

**Comment by aarmey** [comment]
6 components is a lot given the size of the dataset. How much variance does 2 comp explain with PCA?

**Comment by mcreixell** [comment]
55%.

**Comment by mcreixell** [comment]
I'm going to include p-AXL and p-EGFR now. This might change things.

**Comment by mcreixell** [comment]
Now R2X is ~20% with 2 components, PCA ~48%... Any suggestions?

**Comment by aarmey** [comment]
What is the tensor size? You've added things.

**Comment by mcreixell** [comment]
(2, 10, 7, 12)

**Pull request closed without merging**
